### ISSUE TITLE
Expression [?(@.key == 'keyvalue')] throws exception when item of array does not have property

### ISSUE THREAD

**Issue by midweste** [remorhaz/php-json-path#6]
Using **modified** version of the sample data from the README, seems expressions that use a property of the element are not working when one of the array items does not have that property present

To reproduce: remove the category key from the first book
```
      { "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95,
        "key": "keyvalue"
      },
```

```php

require __DIR__ . '/../vendor/autoload.php';

$json = '{ "store": {
    "book": [
      { "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95,
        "key": "keyvalue"
      },
      { "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99,
        "key": "keyvalue"
      },
      { "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99,
        "key": "keyvalue"
      },
      {
        "category": "fiction"
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99,
        "key": "keyvalue"
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
}';


$node = \Remorhaz\JSON\Data\Value\EncodedJson\NodeValueFactory::create()->createValue($json);
$query = \Remorhaz\JSON\Path\Query\QueryFactory::create()->createQuery("$.store.book[?(@.category == 'fiction')]"); // should be working
$result = \Remorhaz\JSON\Path\Processor\Processor::create()->select($query, $node)->decode();
print_r($result);

```

Call Stack

```
Fatal error: Uncaught Remorhaz\JSON\Path\Runtime\Exception\IndexMapMatchFailedException: Index map match failed in /app/vendor/remorhaz/php-json-path/src/Query/Query.php on line 45

Remorhaz\JSON\Path\Query\Exception\QueryExecutionFailedException: Failed to execute JSONPath query: $.store[?(@.category == 'reference')]

return function (Remorhaz\JSON\Path\Value\NodeValueListInterface $input, Remorhaz\JSON\Path\Runtime\ValueListFetcherInterface $valueListFetcher, Remorhaz\JSON\Path\Runtime\EvaluatorInterface $evaluator, Remorhaz\JSON\Path\Runtime\LiteralFactoryInterface $literalFactory, Remorhaz\JSON\Path\Runtime\Matcher\MatcherFactoryInterface $matcherFactory) : Remorhaz\JSON\Path\Value\ValueListInterface {
    $var2 = $matcherFactory->matchPropertyStrictly('store');
    $var3 = $valueListFetcher->fetchChildren($input, $var2);
    $var4 = $valueListFetcher->fetchFilterContext($var3);
    $var5 = $valueListFetcher->splitFilterContext($var4);
    $var8 = $literalFactory->createScalar($var5, 'reference');
    $var6 = $matcherFactory->matchPropertyStrictly('category');
    $var7 = $valueListFetcher->fetchChildren($var5, $var6);
    $var9 = $evaluator->isEqual($var7, $var8);
    $var10 = $evaluator->evaluate($var5, $var9);
    $var11 = $valueListFetcher->joinFilterResults($var10, $var4);
    $var12 = $valueListFetcher->fetchFilteredValues($var4, $var11);
    return $var12;
}; in /app/vendor/remorhaz/php-json-path/src/Query/Query.php on line 45

Call Stack:
    0.0003     412048   1. {main}() /app/public/php-json-path-sample.php:0
    0.0072     534880   2. Remorhaz\JSON\Path\Processor\Processor->select() /app/public/php-json-path-sample.php:54
    0.0072     534880   3. Remorhaz\JSON\Path\Query\LazyQuery->__invoke() /app/vendor/remorhaz/php-json-path/src/Processor/Processor.php:80
    0.0531     964688   4. Remorhaz\JSON\Path\Query\Query->__invoke() /app/vendor/remorhaz/php-json-path/src/Query/LazyQuery.php:32

```

**Comment by remorhaz** [comment]
Fixed in v0.4.2

**Comment by midweste** [comment]
Latest commit does not seem to fix the issue.  I've modified the code to reproduce below and used the "isbn" field for test purposes as it's not present on all books.  Json is from the goessner.json file

```php


require __DIR__ . '/../vendor/autoload.php';

$json = '{
  "store" : {
    "book" : [
      {
        "category" : "reference",
        "author" : "Nigel Rees",
        "title" : "Sayings of the Century",
        "price" : 8.95
      },
      {
        "category" : "fiction",
        "author" : "Evelyn Waugh",
        "title" : "Sword of Honour",
        "price" : 12.99
      },
      {
        "category" : "fiction",
        "author" : "Herman Melville",
        "title" : "Moby Dick",
        "isbn" : "0-553-21311-3",
        "price" : 8.99
      },
      {
        "category" : "fiction",
        "author" : "J. R. R. Tolkien",
        "title" : "The Lord of the Rings",
        "isbn" : "0-395-19395-8",
        "price" : 22.99
      }
    ],
    "bicycle" : {
      "color" : "red",
      "price" : 19.95
    }
  },
  "expensive" : 10
}';


$node = \Remorhaz\JSON\Data\Value\EncodedJson\NodeValueFactory::create()->createValue($json);
$query = \Remorhaz\JSON\Path\Query\QueryFactory::create()->createQuery("$.store.book[?(@.isbn == '0-395-19395-8')]"); // should be working
$result = \Remorhaz\JSON\Path\Processor\Processor::create()->select($query, $node)->decode();
print_r($result);

```

**Comment by midweste** [comment]
Exception for reference:

```
Fatal error: Uncaught Remorhaz\JSON\Path\Runtime\Exception\IndexMapMatchFailedException: Index map match failed in /app/vendor/remorhaz/php-json-path/src/Query/Query.php on line 45

Remorhaz\JSON\Path\Query\Exception\QueryExecutionFailedException: Failed to execute JSONPath query: $.store.book[?(@.isbn == '0-395-19395-8')]

return function (Remorhaz\JSON\Path\Value\NodeValueListInterface $input, Remorhaz\JSON\Path\Runtime\ValueListFetcherInterface $valueListFetcher, Remorhaz\JSON\Path\Runtime\EvaluatorInterface $evaluator, Remorhaz\JSON\Path\Runtime\LiteralFactoryInterface $literalFactory, Remorhaz\JSON\Path\Runtime\Matcher\MatcherFactoryInterface $matcherFactory) : Remorhaz\JSON\Path\Value\ValueListInterface {
    $var4 = $matcherFactory->matchPropertyStrictly('book');
    $var2 = $matcherFactory->matchPropertyStrictly('store');
    $var3 = $valueListFetcher->fetchChildren($input, $var2);
    $var5 = $valueListFetcher->fetchChildren($var3, $var4);
    $var6 = $valueListFetcher->fetchFilterContext($var5);
    $var7 = $valueListFetcher->splitFilterContext($var6);
    $var10 = $literalFactory->createScalar($var7, '0-395-19395-8');
    $var8 = $matcherFactory->matchPropertyStrictly('isbn');
    $var9 = $valueListFetcher->fetchChildren($var7, $var8);
    $var11 = $evaluator->isEqual($var9, $var10);
    $var12 = $evaluator->evaluate($var7, $var11);
    $var13 = $valueListFetcher->joinFilterResults($var12, $var6);
    $var14 = $valueListFetcher->fetchFilteredValues($var6, $var13);
    return $var14;
}; in /app/vendor/remorhaz/php-json-path/src/Query/Query.php on line 45

Call Stack:
    0.0001     411520   1. {main}() /app/public/php-json-path-sample.php:0
    0.0052     534712   2. Remorhaz\JSON\Path\Processor\Processor->select() /app/public/php-json-path-sample.php:46
    0.0052     534712   3. Remorhaz\JSON\Path\Query\LazyQuery->__invoke() /app/vendor/remorhaz/php-json-path/src/Processor/Processor.php:80
    0.0549     966512   4. Remorhaz\JSON\Path\Query\Query->__invoke() /app/vendor/remorhaz/php-json-path/src/Query/LazyQuery.php:32
```

**Comment by midweste** [comment]
Trying to learn about the code see what may be happening, maybe this will help:

Evaluator.php line 184 comparing the two index maps using ->equals:

![image](https://user-images.githubusercontent.com/6331501/63517637-f4b26480-c4b4-11e9-9880-0c336a3e1333.png)

IndexMap.php line 65 comparing the two index map arrays:

![image](https://user-images.githubusercontent.com/6331501/63517852-67234480-c4b5-11e9-9aa0-d8722d39d40a.png)

**Comment by remorhaz** [comment]
Problem confirmed, I'm working on it.

**Comment by remorhaz** [comment]
Fixed in v0.5.0.

**Comment by midweste** [comment]
Nice work, thank you for the fix!
